In [108]:
import numpy as np

np.random.seed(1)


def relu(x):
    return (x > 0) * x


def relu2deriv(output):
    return output > 0

streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1]
])
move = np.array([[1, 1, 0, 0]]).T
alpha = 0.2
hidden_size = 4

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

print(weights_0_1)
print(weights_1_2)

for iter in range(6000):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i : i + 1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        layer_2_error += np.sum((layer_2 - move[i : i + 1]) ** 2)
        
        print(layer_2_error)
        
        layer_2_delta = layer_2 - move[i : i + 1]
        layer_1_delta = layer_2_delta * weights_1_2.T * relu2deriv(layer_1)
        weights_delta_1_2 = layer_1.T.dot(layer_2_delta)
        weights_delta_0_1 = layer_0.T.dot(layer_1_delta)
        
        weights_0_1 -= alpha * weights_delta_0_1
        weights_1_2 -= alpha * weights_delta_1_2
    print(weights_0_1)
    print(weights_1_2)
    print(layer_2_error)
    print('-----------------------------------')





[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
0.3697329913497495
1.3281972624432705
1.4142058374213209
1.4142058374213209
[[-0.16595599  0.53261573 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.24212266]
 [-0.20646505  0.12154675 -0.16161097  0.41649053]]
[[-0.5910955 ]
 [ 0.8093161 ]
 [-0.94522481]
 [ 0.32734528]]
1.4142058374213209
-----------------------------------
0.21497184958404528
1.0846836297669273
1.212716151470694
1.212716151470694
[[-0.16595599  0.6076637  -0.99977125 -0.36498009]
 [-0.70648822 -0.81532281 -0.62747958 -0.1807014 ]
 [-0.20646505  0.13433635 -0.16161097  0.48196768]]
[[-0.5910955 ]
 [ 0.8559077 ]
 [-0.94522481]
 [ 0.33111802]]
1.212716151470694
-----------------------------------
0.10639322529131888
0.8996129444814701
1.0559778908677695
1.056563760006402
[[-0.16595599  0.66

1.5644609518304656e-11
1.5644609518304656e-11
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99253918e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  2.41005531e-06]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11202835]]
1.5644609518304656e-11
-----------------------------------
0.0
2.168089390590482e-12
1.1435348380641028e-11
1.1435348380641028e-11
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99254246e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  2.06048371e-06]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11202861]]
1.1435348380641028e-11
-----------------------------------
0.0
1.584753261297409e-12
8.358607809740121e-12
8.358607809740121e-12
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99254526e-01]
 [-2.06465052e-01 -3.30832380e-02 

0.0
5.9024545080899156e-27
3.117438655566974e-26
3.117438655566974e-26
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.07599870e-13]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
3.117438655566974e-26
-----------------------------------
0.0
4.319802316990261e-27
2.279122308492774e-26
2.279122308492774e-26
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  9.19904355e-14]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
2.279122308492774e-26
-----------------------------------
0.0
3.155887355143234e-27
1.6656010584717577e-26
1.6656010584717577e-26
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.064650

9.860761315902498e-32
9.860761315902498e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315902498e-32
-----------------------------------
0.0
4.930380657631324e-32
9.86076131574425e-32
9.86076131574425e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.86076131574425e-32
-----------------------------------
0.0
4.930380657631324e-32
9.86076131562514e-32
9.86076131562514e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971

[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 

 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860

9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.616

9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.616

[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 

4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860

[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 

 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06

4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.616

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06

4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 

 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860

 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06

9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.616

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 

0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.616

9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e

9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27943911e-01 -6.27479577e-01  8.99256176e-01]
 [-2.06465052e-01 -3.30832380e-02 -1.61610971e-01  1.50290922e-16]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11203017]]
9.860761315262652e-32
-----------------------------------
0.0
4.930380657631324e-32
9.860761315262652e-32
9.860761315262652e-32
[[-1.65955991e-01  9.10567682e-01 -9.99771250e-01 -9.00239250e-01]
 [-7.06488218e-01 -9.27

In [168]:
import numpy as np


np.random.seed(1)

def relu(x):
    return (x > 0) * x 


def relu2deriv(output):
    return output > 0


streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1]
])
move = np.array([[1, 1, 0, 0]]).T
hidden_size = 4
alpha = 0.2
weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

for iter in range(1000):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(layer_0.dot(weights_0_1))
        layer_2 = layer_1.dot(weights_1_2)
        
        layer_2_error += (layer_2 - move[i:i+1]) ** 2
        
        layer_2_delta = layer_2 - move[i:i+1]
        layer_1_delta = layer_2_delta * weights_1_2.T * relu2deriv(layer_1)
        
        
#         print(layer_1_delta)
        weights_delta_1_2 = layer_2_delta * layer_1.T
        weights_delta_0_1 = layer_1_delta * layer_0.T
        
        weights_1_2 -= alpha * weights_delta_1_2
        weights_0_1 -= alpha * weights_delta_0_1
    if iter % 10 == 9:
        print(np.sum(layer_2_error))
        

        
test = np.array([[1, 0, 0]])
print(test)
print(weights_0_1)
print(test.dot(weights_0_1))
layer_1 = relu(test.dot(weights_0_1))
layer_2 = layer_1.dot(weights_1_2)
print(layer_2)

0.6342311598444467
0.35838407676317513
0.0830183113303298
0.006467054957103705
0.0003292669000750734
1.5055622665134859e-05
6.623830121108468e-07
2.8900540237497683e-08
1.2587641233552748e-09
5.480552259746703e-11
2.3860043209091744e-12
1.0387504595876368e-13
4.522200282839368e-15
1.9687385946013715e-16
8.570895916698259e-18
3.73133512041459e-19
1.6244351039525356e-20
7.072028248288851e-22
3.0788824402436473e-23
1.3402291739809955e-24
5.83686839328961e-26
2.546223017433715e-27
1.1254869590407588e-28
5.1626830664398075e-30
4.267860485901025e-31
1.113074180403234e-31
9.889399465277358e-32
9.862430265455444e-32
9.860858701978964e-32
9.860766998406552e-32
9.860761646912255e-32
9.860761334616633e-32
9.860761316392083e-32
9.860761315328555e-32
9.860761315266495e-32
9.860761315262873e-32
9.86076131526266e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315262652e-32
9.860761315

In [31]:
import numpy as np


np.random.seed(1)


def relu(x):
    return (x > 0) * x


def relu2deriv(output):
    return output > 0


alpha = 0.2
streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1],
    [1, 1, 0],
    [0, 0, 0],
    [1, 0, 0]
])
move = np.array([[1, 1, 0, 0, 0, 0, 1]]).T

weights_0_1 = 2 * np.random.random((3, 4)) - 1
weights_1_2 = 2 * np.random.random((4, 1)) - 1


for iter in range(1000):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i: i + 1]
        layer_1 = relu(layer_0.dot(weights_0_1))
        layer_2 = layer_1.dot(weights_1_2)
        
        layer_2_error += np.sum((layer_2 - move[i: i + 1]) ** 2)
        
        layer_2_delta = layer_2 - move[i: i + 1]
        layer_1_delta = layer_2_delta * weights_1_2.T * relu2deriv(layer_1)
        weights_delta_1_2 = layer_2_delta * layer_1.T
        weights_delta_0_1 = layer_1_delta * layer_0.T
        
        weights_1_2 -= alpha * weights_delta_1_2
        weights_0_1 -= alpha * weights_delta_0_1
    if iter % 10 == 9:
        print("Error: ", layer_2_error)
        

input = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1],
    [1, 1, 0],
    [0, 0, 0],
    [1, 0, 0]
])  
print(relu(input.dot(weights_0_1)).dot(weights_1_2))

Error:  0.5700290237343386
Error:  0.27105537663698587
Error:  0.04658614714587637
Error:  0.0031290238513392503
Error:  0.00015479944933220966
Error:  6.996945566208686e-06
Error:  3.079541343767593e-07
Error:  1.347737736188944e-08
Error:  5.891359202845568e-10
Error:  2.5747055826147142e-11
Error:  1.1252007638228128e-12
Error:  4.9174999519879225e-14
Error:  2.1492108005465622e-15
Error:  9.393786983731825e-17
Error:  4.1061729642286615e-18
Error:  1.7950572764817018e-19
Error:  7.848298717035598e-21
Error:  3.4320414410449164e-22
Error:  1.5011629628355755e-23
Error:  6.567178554021889e-25
Error:  2.872597045149629e-26
Error:  1.250938029157453e-27
Error:  5.443512748741864e-29
Error:  2.1782768413097426e-30
Error:  3.0317017150441293e-31
Error:  1.4972786353345928e-31
Error:  1.4801705734621466e-31
Error:  1.4791761285437376e-31
Error:  1.4791178298019363e-31
Error:  1.4791144103565256e-31
Error:  1.4791142097869935e-31
Error:  1.4791141980224518e-31
Error:  1.4791141973323949e-3